---
title: "Agile Research"
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', dev = "svg")
```

class: title-slide center middle inverse

# Agile Research

## How to work efficiently, even from `r icon::fa_home()`

<br>

### Florian Privé

#### NCRR WIP -- October 2, 2020

---

## About me

<br>

My background to understand where this talk is coming from:

--

- Engineer in Informatics and Applied Mathematics from France $\rightarrow$ I could have been developing software for companies instead of doing Research

--

- PhD in predictive human genetics

--

- Just started my second year as a postdoc at NCRR

--

- Now have the perspective as both first author and (co-)supervisor


---

## Agile workflow

<br>

- Primarily developed for software development

- A response to the problem of many teams failing to deliver a working product in time, and funders pulling money out because they lost confidence or/and interest in the project over time

<br>

--

$\Rightarrow$ What is the best workflow to turn an idea into reality?

---

## Agile workflow in Research?

<br>

A crude analogy:

--

- the team $\longrightarrow$ the first author(s)

--

- the final product $\longrightarrow$ the paper

--

- a working component of the product $\longrightarrow$ a figure or table of the paper

--

- stakeholders/funders $\longrightarrow$ the supervisor(s)

--

<br>

$\Rightarrow$ What is the best workflow to turn an idea into a paper?

---

## The main component of an Agile workflow: the sprint

<br>

--

- One element of the *TODO* list, which **should not take very long**    
(say one week or two max).

--

- You should try to further subdivide this sprint into even smaller tasks.

--

- Once you start one of these tasks, you should try to **focus** only on this, until completion.

--

- It is important to always set a **maximum time limit** for a task or a sprint. 

--

    - If you can't finish in time, maybe you need help?
    
--
    
    - If you are exploring an idea, maybe it just does not work and you should move on to another idea?    
--
    $\Rightarrow$ try to **fail fast** and move on    
    `r icon::fa_info_circle()` only 1 out of 10 of my promising ideas actually end up in a paper!
    
---

## Another Agile principle: deliver fast and regularly

<br>

I'm not saying you should draft a paper within two weeks but..

<br>

--

- Deliver a proof of concept quickly, or move on to another idea

--

- Deliver regularly, e.g. one figure or table that could go into the paper

--

- Keep the supervisor(s) enthusiastic and confident about the work, and keep you motivated as well

--

- Get feedback sooner to avoid going in the wrong direction for weeks

--

- Welcome updates on your analysis $\Rightarrow$ this will make your code more reproducible if you know you may have to update it later.

--

<br>

$\Rightarrow$ Agile provides speed and energy!

---

## Also part of the Agile workflow: the stand-ups

<br>

--

Everyday, everyone quickly says 

- what they have been working on

- what they will be working on (e.g. planning the task(s) of the day)

- if they are stuck somehow (need help, feedback maybe?)

--

<br>

- Bjarni, Clara, Emil and I had these stand-ups on Zoom during the first lockdown.

- It helped keeping everyone on track while working from home.

- Should continue doing it? Not always possible? Maybe opt for a written alternative?

---

## Summary and conclusion

<br>

--

- Design small tasks that you can do quickly.

--

- For exploratory analyses, set a time limit beforehand.

--

- Deliver as early and regularly as possible, to keep everyone on track and motivated by the Research project.

<br>

--

- The Agile methodology is a tried-and-tested method in the Industry.

--

-  This is basically how I try to work and how (I think) I remain effective, even when working from home.

<br>

--

`r icon::fa_info_circle()` I am moving back to France in 2 months, and I'll be working remotely from there for the last 10 months of my contract.


---
class: center, middle, inverse

# Thanks

<br>

Presentation available at    
https://privefl.github.io/thesis-docs/agile-research.html

<br>

Some inspiration from *Agile Data Science with R: a workflow* by Edwin Thoen, available at https://edwinth.github.io/ADSwR/

<br>

<br>

`r icon::fa("twitter")` [privefl](https://twitter.com/privefl) &nbsp;&nbsp;&nbsp;&nbsp; `r icon::fa("github")` [privefl](https://github.com/privefl) &nbsp;&nbsp;&nbsp;&nbsp; `r icon::fa("stack-overflow")` [F. Privé](https://stackoverflow.com/users/6103040/f-priv%c3%a9)

.footnote[Slides created via R package [**xaringan**](https://github.com/yihui/xaringan)]
